---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-toolkit
  labels:
    app: devops-toolkit
    component: web
  annotations:
    app.komodor.com/deploy.link.argocd: "http://argo-cd.34.138.223.93.nip.io/applications/devops-toolkit"
spec:
  replicas: 20
  selector:
    matchLabels:
      app: devops-toolkit
      component: web
  template:
    metadata:
      labels:
        app: devops-toolkit
        component: web
    spec:
      containers:
      - name: devops-toolkit
        image: vfarcic/devops-toolkit-series
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi
